version: '3.8'
services:
  db:
    image: postgres:16.1
    container_name: shareit-db
    ports:
      - "5669:5432"
    environment:
      - POSTGRES_DB=shareit-name-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  server:
    build: server
    ports:
      - "9091:9090"
    depends_on:
      - db
    environment:
      - U_PROFILE=dev
      - U_PORT=9090
      - DB_NAME=shareit-name-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
#      - TZ=Europe/Samara
#      - PGTZ=Europe/Samara

  gateway:
    build: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - S_SERVER_URL=http://server:9090