
--drop table IF EXISTS users, items_request, items, bookings, comments;

create TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  email varchar(256) UNIQUE NOT NULL
);

create TABLE IF NOT EXISTS items_request (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar(255),
  requestor_id integer NOT NULL,
  created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT items_request_requestor_id FOREIGN KEY (requestor_id) REFERENCES users(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(255),
  available boolean NOT NULL,
  owner_id integer NOT NULL,
  request_id integer,
  CONSTRAINT items_owner_id FOREIGN KEY (owner_id) REFERENCES users(id) ON delete CASCADE,
  CONSTRAINT items_request_id FOREIGN KEY (request_id) REFERENCES items_request(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS bookings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_time  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id integer NOT NULL,
  booker_id integer NOT NULL,
  status varchar(55) NOT NULL,
  CONSTRAINT bookings_item_id FOREIGN KEY (item_id) REFERENCES items(id) ON delete CASCADE,
  CONSTRAINT bookings_booker_id FOREIGN KEY (booker_id) REFERENCES users(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text varchar(255) NOT NULL,
  item_id integer NOT NULL,
  author_id integer NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT comments_item_id FOREIGN KEY (item_id) REFERENCES items(id) ON delete CASCADE,
  CONSTRAINT comments_author_id FOREIGN KEY (author_id) REFERENCES users(id) ON delete CASCADE
);

